export const GameFilterList = [
    { name: "All", selector: "*" },
    { name: "Porting", selector: ".category-porting" },
    { name: "Development", selector: ".category-development" },
    { name: "Quality Assurance", selector: ".category-qa" },
];

export const GameFilterList2 = [
    { name: "All", selector: "*" },
    { name: "Professional Experience", selector: ".category-professional" },
    { name: "Education", selector: ".category-education" },
    { name: "Game Jams", selector: ".category-jams" },
];

export const GamesList = [
    { category: ["porting"], name: "American Arcadia", tag: "Porting", platforms: ["switch", "ps4", "xsx"], hasSection: true },
    { category: ["development", "porting"], name: "Metamorphosis VR", tag: "Porting, Development", platforms: ["quest"], hasSection: true },
    { category: ["porting"], name: "Xuan Yuan Sword 7", tag: "Porting", platforms: ["switch"], hasSection: true },
    { category: ["porting"], name: "Togges", tag: "Porting", platforms: ["switch", "xbo"], hasSection: true },
    { category: ["porting"], name: "Hell Pie", tag: "Porting", platforms: ["xbo", "xsx"], hasSection: true },
    { category: ["porting"], name: "Firegirl: Hack 'n Splash Rescue DX", tag: "Porting", platforms: ["switch"], hasSection: true },
    { category: ["porting"], name: "Unpublished Game #1", tag: "Porting, Development", platforms: ["switch", "xbo", "xsx", "ps4", "ps5", "steam"], hasSection: true },
    { category: ["development", "jams"], name: "Quantum Fields", tag: "Development, Game Jams", platforms: ["pc"], hasSection: true },
    { category: ["development", "education"], name: "Ronin-Hood Sisters", tag: "Development, Education", platforms: ["pc"], hasSection: true },
    { category: ["development", "education"], name: "Unity Zombie Killer", tag: "Development, Education", platforms: ["pc"], hasSection: true },
    { category: ["development", "education"], name: "Medieval Floor", tag: "Development, Education", platforms: ["pc"], hasSection: true },
    { category: ["qa"], name: "Divinity Original Sin II", tag: "QA", platforms: ["switch"] },
    { category: ["qa"], name: "Spelunky 2", tag: "QA", platforms: ["ps4", "steam"] },
    { category: ["qa"], name: "Braid, Anniversary Edition", tag: "QA", platforms: ["ps4", "xbo", "switch"] },
    { category: ["qa"], name: "Rebel Galaxy Outlaw", tag: "QA", platforms: ["switch"] },
    { category: ["qa"], name: "Battle Brothers", tag: "QA", platforms: ["switch"] },
    { category: ["qa"], name: "Starbound", tag: "QA", platforms: ["win10"] },
    { category: ["qa"], name: "Heroes of Hammerwatch", tag: "QA", platforms: ["ps4", "xbo", "switch", "steam"] },
    { category: ["qa"], name: "eSports Life Tycoon", tag: "QA", platforms: ["steam"] },
    { category: ["qa"], name: "Rädical Rabbit Stew", tag: "QA", platforms: ["steam", "ps4", "xbo", "steam"] },
    { category: ["qa"], name: "Invisible, Inc", tag: "QA", platforms: ["ps4", "switch", "apple"] },
    { category: ["qa"], name: "Gold Rush: The Game", tag: "QA", platforms: ["ps4", "xbo"] },
    { category: ["qa"], name: "Sunless Skies", tag: "QA", platforms: ["ps4", "xbo"] },
    { category: ["qa"], name: "Youtubers Life Omg!", tag: "QA", platforms: ["steam", "ps4", "xbo"] },
    { category: ["qa"], name: "Youtubers Life 2", tag: "QA", platforms: ["steam", "ps4", "xbo"] },
    { category: ["qa"], name: "Super Animal Royale", tag: "QA", platforms: ["switch"] },
    { category: ["qa"], name: "Kingdom Rush Frontiers", tag: "QA", platforms: ["switch"] },
    { category: ["qa"], name: "Out of Space: Couch Edition", tag: "QA", platforms: ["ps4", "xbo"] },
    { category: ["qa"], name: "Jump Step Step", tag: "QA", platforms: ["ps4"] },
    { category: ["qa"], name: "Oddmar", tag: "QA", platforms: ["switch"] },
    { category: ["qa"], name: "Streets of Rage 4", tag: "QA", platforms: ["xbo", "win10"] },
    { category: ["qa"], name: "Gris", tag: "QA", platforms: ["ps4", "apple"] },
    { category: ["qa"], name: "Fight'N Rage", tag: "QA", platforms: ["switch", "ps4", "xbo"] },
    { category: ["qa"], name: "They Are Billions", tag: "QA", platforms: ["ps4", "xbo"] },
    { category: ["qa"], name: "Trine Enchanted Edition", tag: "QA", platforms: ["switch", "xbo"] },
    { category: ["qa"], name: "Trine 2: Complete Story", tag: "QA", platforms: ["switch", "xbo"] },
    { category: ["qa"], name: "Trine 3: The Artifacts of Power", tag: "QA", platforms: ["switch", "xbo"] },
    { category: ["qa"], name: "Ancestors Legacy", tag: "QA", platforms: ["ps4"] },
    { category: ["qa"], name: "Wargroove", tag: "QA", platforms: ["xbo", "ps4", "win10"] },
    { category: ["qa"], name: "Super Skelemania", tag: "QA", platforms: ["switch"] },
    { category: ["qa"], name: "Spell Casting", tag: "QA", platforms: ["switch"] },
    { category: ["qa"], name: "Aurion: Legacy of the Kori-Odan", tag: "QA", platforms: ["xbo"] },
    { category: ["qa"], name: "Table Top Racing: World Tour", tag: "QA", platforms: ["switch"] },
    { category: ["qa"], name: "Path to Mnemosyne", tag: "QA", platforms: ["switch", "ps4"] },
    { category: ["qa"], name: "Salt and Sanctuary", tag: "QA", platforms: ["switch", "xbo"] },
    { category: ["qa"], name: "Rogue Legacy", tag: "QA", platforms: ["switch"] },
    { category: ["qa"], name: "Full Metal Furies", tag: "QA", platforms: ["switch", "xbo", "win10"] },
    { category: ["qa"], name: "Windjammers", tag: "QA", platforms: ["switch"] },
    { category: ["qa"], name: "Tricky Towers", tag: "QA", platforms: ["switch", "xbo"] },
    { category: ["qa"], name: "Pushy and Pully in Blockland", tag: "QA", platforms: ["switch"] },
    { category: ["qa"], name: "Amnesia: Collection", tag: "QA", platforms: ["ps4", "xbo"] },
    { category: ["qa"], name: "Broken Age", tag: "QA", platforms: ["switch", "xbo"] },
    { category: ["qa"], name: "Bastion", tag: "QA", platforms: ["switch", "xbo"] },
    { category: ["qa"], name: "Gone Home", tag: "QA", platforms: ["switch", "apple"] },
    { category: ["qa"], name: "ELEA", tag: "QA", platforms: ["xbo"] },
    { category: ["qa"], name: "Hyper Light Drifter: Special Edition", tag: "QA", platforms: ["switch"] },
    { category: ["qa"], name: "Sunless Sea", tag: "QA", platforms: ["apple", "ps4"] },
    { category: ["qa"], name: "de Blob", tag: "QA", platforms: ["switch", "ps4", "xbo", "steam"] },
    { category: ["qa"], name: "de Blob 2", tag: "QA", platforms: ["switch", "ps4", "xbo", "steam"] },
    { category: ["qa"], name: "The Journey Down Chapter One", tag: "QA", platforms: ["switch", "ps4", "xbo"] },
    { category: ["qa"], name: "The Journey Down Chapter Two", tag: "QA", platforms: ["switch", "ps4", "xbo"] },
    { category: ["qa"], name: "The Journey Down Chapter Three", tag: "QA", platforms: ["switch", "ps4", "xbo"] },
    { category: ["qa"], name: "n++", tag: "QA", platforms: ["switch"] },
    { category: ["qa"], name: "Owlboy", tag: "QA", platforms: ["switch", "xbo", "ps4"] },
    { category: ["qa"], name: "bit Dungeon +", tag: "QA", platforms: ["ps4", "vita"] },
    { category: ["qa"], name: "Rad Rodgers", tag: "QA", platforms: ["ps4", "xbo"] },
    { category: ["qa"], name: "SOMA", tag: "QA", platforms: ["ps4", "xbo"] },
    { category: ["qa"], name: "OlliOlli: Switch Stance", tag: "QA", platforms: ["switch"] },
    { category: ["qa"], name: "Hob", tag: "QA", platforms: ["ps4"] },
    { category: ["qa"], name: "Symmetry", tag: "QA", platforms: ["xbo", "ps4"] },
    { category: ["qa"], name: "Kerbal Space Program Enhanced Edition", tag: "QA", platforms: ["xbo", "ps4"] },
    { category: ["qa"], name: "Hammerwatch", tag: "QA", platforms: ["switch", "ps4", "xbo"] },
    { category: ["qa"], name: "Fez Pocket Edition", tag: "QA", platforms: ["apple"] },
    { category: ["qa"], name: "Don't Starve Together", tag: "QA", platforms: ["xbo"] },
    { category: ["qa"], name: "Baja: Edge of Control HD", tag: "QA", platforms: ["ps4", "xbo", "steam"] },
    { category: ["qa"], name: "Hole New World", tag: "QA", platforms: ["ps4"] },
    { category: ["qa"], name: "Talisman: Digital Edition", tag: "QA", platforms: ["ps4", "vita"] },
    { category: ["qa"], name: "Clicker Heroes", tag: "QA", platforms: ["ps4", "xbo"] },
    { category: ["qa"], name: "Super Meat Boy", tag: "QA", platforms: ["switch", "wiiu"] },
    { category: ["qa"], name: "Kholat", tag: "QA", platforms: ["xbo"] },
    { category: ["qa"], name: "Crypt of the Necrodancer", tag: "QA", platforms: ["switch", "ps4", "xbo", "apple"] },
    { category: ["qa"], name: "Cannon Brawl", tag: "QA", platforms: ["ps4", "xbo"] },
    { category: ["qa"], name: "Don't Starve: Console Edition", tag: "QA", platforms: ["switch", "ps4", "xbo", "apple", "android"] },
    { category: ["qa"], name: "Reus", tag: "QA", platforms: ["ps4", "xbo"] },
    { category: ["qa"], name: "Axiom Verge", tag: "QA", platforms: ["wiiu"] },
    { category: ["development", "jams"], name: "Pengüin", tag: "Development, Game Jams", platforms: ["pc"], hasSection: true},
    { category: ["development", "jams"], name: "Purramid", tag: "Development, Game Jams", platforms: ["pc"], hasSection: true },
    { category: ["development", "education"], name: "Griddle", tag: "Development, Education", platforms: ["pc"], hasSection: true },
];

export const PersonalProjectsFilterList = [
    { name: "All", selector: "*" },
    { name: "Unreal Plugins", selector: ".category-plugin" },
    { name: "Game Mod/Addons", selector: ".category-mod" },
    { name: "Game Jams", selector: ".category-jams" },
];

export const PersonalProjectsList = [
    { category: ["plugin"], name: "Unused Node Cleaner", tag: "Unreal Plugin", platforms: ["windows", "apple", "linux"], hasSection: true },
    { category: ["development", "jams"], name: "Quantum Fields", tag: "Game", platforms: ["pc"], hasSection: true },
    { category: ["mod"], name: "Urkaz Moon Tools", tag: "Minecraft Mod", hasSection: true },
    { category: ["mod"], name: "Item Name Localized", tag: "World of Warcraft Addon", hasSection: true },
    { category: ["development", "jams"], name: "Pengüin", tag: "Game", platforms: ["pc"], hasSection: true},
    { category: ["development", "jams"], name: "Purramid", tag: "Game", platforms: ["pc"], hasSection: true },
];

export function cleanText(text) {
    const cleanedText = text
        .toLowerCase()
        .replace(/[^a-z0-9]/g, '');

    return cleanedText;
}


export default GamesList;