export const GameFilterList = [
    { name: "All", selector: "*" },
    { name: "Porting", selector: ".category-porting" },
    { name: "Development", selector: ".category-development" },
    { name: "Quality Assurance", selector: ".category-qa" },
];

export const GamesList = [
    { category: ["porting"], name: "Xuan Yuan Sword 7", tag: "Porting" },
    { category: ["porting"], name: "Togges", tag: "Porting" },
    { category: ["porting"], name: "Hell Pie", tag: "Porting" },
    { category: ["porting", "development"], name: "Metamorphosis VR", tag: "Porting, Development" },
    { category: ["porting"], name: "Firegirl: Hack 'n Splash Rescue DX", tag: "Porting" },
    { category: ["porting"], name: "American Arcadia", tag: "Porting" },
    { category: ["porting", "development"], name: "Unpublished #1", tag: "Porting, Development" },
    { category: ["qa"], name: "Spelunky 2", tag: "QA" },
    { category: ["qa"], name: "Braid, Anniversary Edition", tag: "QA" },
    { category: ["qa"], name: "Rebel Galaxy Outlaw", tag: "QA" },
    { category: ["qa"], name: "Battle Brothers", tag: "QA" },
    { category: ["qa"], name: "Starbound", tag: "QA" },
    { category: ["qa"], name: "Heroes of Hammerwatch", tag: "QA" },
    { category: ["qa"], name: "eSports Life Tycoon", tag: "QA" },
    { category: ["qa"], name: "Rädical Rabbit Stew", tag: "QA" },
    { category: ["qa"], name: "Invisible, Inc", tag: "QA" },
    { category: ["qa"], name: "Gold Rush", tag: "QA" },
    { category: ["qa"], name: "Sunless Skies", tag: "QA" },
    { category: ["qa"], name: "Youtubers Life Omg!", tag: "QA" },
    { category: ["qa"], name: "Youtubers Life 2", tag: "QA" },
    { category: ["qa"], name: "Super Animal Royale", tag: "QA" },
    { category: ["qa"], name: "Kingdom Rush Frontiers", tag: "QA" },
    { category: ["qa"], name: "Out of Space", tag: "QA" },
    { category: ["qa"], name: "Jump Step Step", tag: "QA" },
    { category: ["qa"], name: "Oddmar", tag: "QA" },
    { category: ["qa"], name: "Streets of Rage 4", tag: "QA" },
    { category: ["qa"], name: "Gris", tag: "QA" },
    { category: ["qa"], name: "Fight'N Rage", tag: "QA" },
    { category: ["qa"], name: "Divinity Original Sin II", tag: "QA" },
    { category: ["qa"], name: "They Are Billions", tag: "QA" },
    { category: ["qa"], name: "Trine Enchanted Edition", tag: "QA" },
    { category: ["qa"], name: "Trine 2: Complete Story", tag: "QA" },
    { category: ["qa"], name: "Trine 3: The Artifacts of Power", tag: "QA" },
    { category: ["qa"], name: "Ancestors Legacy", tag: "QA" },
    { category: ["qa"], name: "Wargroove", tag: "QA" },
    { category: ["qa"], name: "Super Skelemania", tag: "QA" },
    { category: ["qa"], name: "Spell Casting", tag: "QA" },
    { category: ["qa"], name: "Aurion: Legacy of the Kori-Odan", tag: "QA" },
    { category: ["qa"], name: "Table Top Racing: World Tour", tag: "QA" },
    { category: ["qa"], name: "Path to Mnemosyne", tag: "QA" },
    { category: ["qa"], name: "Salt & Sanctuary", tag: "QA" },
    { category: ["qa"], name: "Rogue Legacy", tag: "QA" },
    { category: ["qa"], name: "Full Metal Furies", tag: "QA" },
    { category: ["qa"], name: "Windjammers", tag: "QA" },
    { category: ["qa"], name: "Ticky Towers", tag: "QA" },
    { category: ["qa"], name: "Pushy and Pully in Blockland", tag: "QA" },
    { category: ["qa"], name: "Amnesia Collection", tag: "QA" },
    { category: ["qa"], name: "Broken Age", tag: "QA" },
    { category: ["qa"], name: "Bastion", tag: "QA" },
    { category: ["qa"], name: "Gone Home", tag: "QA" },
    { category: ["qa"], name: "ELEA", tag: "QA" },
    { category: ["qa"], name: "Hyper Light Drifter: Special Edition", tag: "QA" },
    { category: ["qa"], name: "Sunles Sea", tag: "QA" },
    { category: ["qa"], name: "de Blob", tag: "QA" },
    { category: ["qa"], name: "de Blob 2", tag: "QA" },
    { category: ["qa"], name: "The Journey Down Chapter One", tag: "QA" },
    { category: ["qa"], name: "The Journey Down Chapter Two", tag: "QA" },
    { category: ["qa"], name: "The Journey Down Chapter Three", tag: "QA" },
    { category: ["qa"], name: "n++", tag: "QA" },
    { category: ["qa"], name: "Owlboy", tag: "QA" },
    { category: ["qa"], name: "bit Dungeon +", tag: "QA" },
    { category: ["qa"], name: "Rad Rodgets", tag: "QA" },
    { category: ["qa"], name: "SOMA", tag: "QA" },
    { category: ["qa"], name: "OlliOlli: Switch Stance", tag: "QA" },
    { category: ["qa"], name: "Hob", tag: "QA" },
    { category: ["qa"], name: "Symmetry", tag: "QA" },
    { category: ["qa"], name: "Keral Space Program", tag: "QA" },
    { category: ["qa"], name: "Hammerwatch", tag: "QA" },
    { category: ["qa"], name: "Fez", tag: "QA" },
    { category: ["qa"], name: "Don't Starve Together", tag: "QA" },
    { category: ["qa"], name: "Baja: Edge of Control HD", tag: "QA" },
    { category: ["qa"], name: "Hole New World", tag: "QA" },
    { category: ["qa"], name: "Talisman: Digital Edition", tag: "QA" },
    { category: ["qa"], name: "Clicker Heroes", tag: "QA" },
    { category: ["qa"], name: "Super Meat Boy", tag: "QA" },
    { category: ["qa"], name: "Kholat", tag: "QA" },
    { category: ["qa"], name: "Crypt of the Necrodancer: Amplified", tag: "QA" },
    { category: ["qa"], name: "Crypt of the Necrodancer", tag: "QA" },
    { category: ["qa"], name: "Cannon Brawl", tag: "QA" },
    { category: ["qa"], name: "Don't Starve: Nintendo Switch Edition", tag: "QA" },
    { category: ["qa"], name: "Don't Starve: Shipwrecked", tag: "QA" },
    { category: ["qa"], name: "Don't Starve: Pocket Edition", tag: "QA" },
    { category: ["qa"], name: "Reus", tag: "QA" },
    { category: ["qa"], name: "Axiom Verge", tag: "QA" },
];

export const PersonalGamesList = [
    { category: ["development"], name: "Quantum Fields", tag: "Development" },
    { category: ["development"], name: "Ronin-Hood Sisters", tag: "Development" },
    { category: ["development"], name: "Unity Zombie Killer", tag: "Development" },
    { category: ["development"], name: "Medieval Floor", tag: "Development" },
    { category: ["development"], name: "Pengüin", tag: "Development" },
    { category: ["development"], name: "Griddle", tag: "Development" },
];

export function cleanText(text) {
    const cleanedText = text
        .toLowerCase()
        .replace(/[^a-z0-9]/g, '');

    return cleanedText;
}


export default GamesList;